.TH "Cell" 3 "Tue May 31 2022" "Version v1.2" "FJSSP - Parte II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell \- Estrutura de dados para representar um plano de produção\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBjobID\fP"
.br
.ti -1c
.RI "int \fBoperationID\fP"
.br
.ti -1c
.RI "int \fBinitialTime\fP"
.br
.ti -1c
.RI "int \fBfinalTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de dados para representar um plano de produção\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FJSSP - Parte II from the source code\&.
