.TH "Execution" 3 "Tue May 31 2022" "Version v1.2" "FJSSP - Parte II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Execution \- Estrutura de dados para representar a lista das execuções das operações em máquinas (em memória)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoperationID\fP"
.br
.ti -1c
.RI "int \fBmachineID\fP"
.br
.ti -1c
.RI "int \fBruntime\fP"
.br
.ti -1c
.RI "struct \fBExecution\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de dados para representar a lista das execuções das operações em máquinas (em memória) 

.SH "Author"
.PP 
Generated automatically by Doxygen for FJSSP - Parte II from the source code\&.
