.TH "ExecutionNode" 3 "Tue May 31 2022" "Version v1.2" "FJSSP - Parte II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExecutionNode \- Estrutura de dados para representar cada nó (posição) da tabela hash das execuções (em memória)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBExecution\fP * \fBstart\fP"
.br
.ti -1c
.RI "int \fBnumberOfExecutions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de dados para representar cada nó (posição) da tabela hash das execuções (em memória) 

.SH "Author"
.PP 
Generated automatically by Doxygen for FJSSP - Parte II from the source code\&.
