.TH "FileExecution" 3 "Tue May 31 2022" "Version v1.2" "FJSSP - Parte II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileExecution \- Estrutura de dados para armazenar em ficheiro a lista de execuções das operações em máquinas\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoperationID\fP"
.br
.ti -1c
.RI "int \fBmachineID\fP"
.br
.ti -1c
.RI "int \fBruntime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de dados para armazenar em ficheiro a lista de execuções das operações em máquinas\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FJSSP - Parte II from the source code\&.
