.TH "Job" 3 "Tue May 31 2022" "Version v1.2" "FJSSP - Parte II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Job \- Estrutura de dados para representar a lista de trabalhos (em memória)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "struct \fBJob\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de dados para representar a lista de trabalhos (em memória) 

.SH "Author"
.PP 
Generated automatically by Doxygen for FJSSP - Parte II from the source code\&.
